var annotated_dup =
[
    [ "recpp", null, [
      [ "EventLoop", "classrecpp_1_1_event_loop.html", "classrecpp_1_1_event_loop" ],
      [ "Schedulable", "classrecpp_1_1_schedulable.html", "classrecpp_1_1_schedulable" ],
      [ "SchedulableQueue", "classrecpp_1_1_schedulable_queue.html", "classrecpp_1_1_schedulable_queue" ],
      [ "Scheduler", "classrecpp_1_1_scheduler.html", "classrecpp_1_1_scheduler" ],
      [ "ThreadPool", "classrecpp_1_1_thread_pool.html", "classrecpp_1_1_thread_pool" ],
      [ "ThreadPoolWorker", "classrecpp_1_1_thread_pool_worker.html", "classrecpp_1_1_thread_pool_worker" ],
      [ "WorkerThread", "classrecpp_1_1_worker_thread.html", "classrecpp_1_1_worker_thread" ],
      [ "AndThen", "classrecpp_1_1_and_then.html", "classrecpp_1_1_and_then" ],
      [ "Filter", "classrecpp_1_1_filter.html", "classrecpp_1_1_filter" ],
      [ "FlatMap", "classrecpp_1_1_flat_map.html", "classrecpp_1_1_flat_map" ],
      [ "Map", "classrecpp_1_1_map.html", "classrecpp_1_1_map" ],
      [ "ObserveOn", "classrecpp_1_1_observe_on.html", "classrecpp_1_1_observe_on" ],
      [ "SubscribeOn", "classrecpp_1_1_subscribe_on.html", "classrecpp_1_1_subscribe_on" ],
      [ "Tap", "classrecpp_1_1_tap.html", "classrecpp_1_1_tap" ],
      [ "CreatePublisher", "classrecpp_1_1_create_publisher.html", "classrecpp_1_1_create_publisher" ],
      [ "DeferPublisher", "classrecpp_1_1_defer_publisher.html", "classrecpp_1_1_defer_publisher" ],
      [ "EmptyPublisher", "classrecpp_1_1_empty_publisher.html", "classrecpp_1_1_empty_publisher" ],
      [ "ErrorPublisher", "classrecpp_1_1_error_publisher.html", "classrecpp_1_1_error_publisher" ],
      [ "JustPublisher", "classrecpp_1_1_just_publisher.html", "classrecpp_1_1_just_publisher" ],
      [ "NeverPublisher", "classrecpp_1_1_never_publisher.html", "classrecpp_1_1_never_publisher" ],
      [ "RangePublisher", "classrecpp_1_1_range_publisher.html", "classrecpp_1_1_range_publisher" ],
      [ "Maybe", "classrecpp_1_1_maybe.html", "classrecpp_1_1_maybe" ],
      [ "Observable", "classrecpp_1_1_observable.html", "classrecpp_1_1_observable" ],
      [ "Single", "classrecpp_1_1_single.html", "classrecpp_1_1_single" ],
      [ "Completable", "classrecpp_1_1_completable.html", "classrecpp_1_1_completable" ],
      [ "MaybeSubscriber", "classrecpp_1_1_maybe_subscriber.html", "classrecpp_1_1_maybe_subscriber" ],
      [ "ObservableSubscriber", "classrecpp_1_1_observable_subscriber.html", "classrecpp_1_1_observable_subscriber" ],
      [ "SingleSubscriber", "classrecpp_1_1_single_subscriber.html", "classrecpp_1_1_single_subscriber" ],
      [ "CompletableSubscriber", "classrecpp_1_1_completable_subscriber.html", "classrecpp_1_1_completable_subscriber" ],
      [ "DefaultSubscriber", "classrecpp_1_1_default_subscriber.html", "classrecpp_1_1_default_subscriber" ],
      [ "EmptySubscription", "classrecpp_1_1_empty_subscription.html", "classrecpp_1_1_empty_subscription" ],
      [ "FilterSubscription", "classrecpp_1_1_filter_subscription.html", "classrecpp_1_1_filter_subscription" ],
      [ "ForwardSubscription", "classrecpp_1_1_forward_subscription.html", "classrecpp_1_1_forward_subscription" ],
      [ "JustSubscription", "classrecpp_1_1_just_subscription.html", "classrecpp_1_1_just_subscription" ],
      [ "NeverSubscription", "classrecpp_1_1_never_subscription.html", "classrecpp_1_1_never_subscription" ],
      [ "RangeSubscription", "classrecpp_1_1_range_subscription.html", "classrecpp_1_1_range_subscription" ]
    ] ]
];